version: "3.8"

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host  # necessário para detectar dispositivos locais (como Sonoff)
    privileged: true    # permite acesso a recursos do sistema (ex: USB, rede)
    volumes:
      - ./ha_config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
